### ISSUE TITLE
(node:10137) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Stonewalling** [Revadike/epicgames-freebies-claimer#100]
### Details
when I was run npm start then I go the error message

**Comment by Revadike** [comment]
Try https://github.com/Revadike/epicgames-freebies-claimer/wiki/Updating-EpicGames-Freebies-Claimer#updating-or-reinstalling-epicgames-freebies-claimer

**Comment by Revadike** [comment]
@Stonewalling is it fixed?

**Comment by Stonewalling** [comment]
> @Stonewalling is it fixed?

I run it on the server,

**Comment by ZainCheung** [comment]
I‘m also got this bug, the program was running on Win10 and it still happened when I tried to update the software and run it again.
I borrowed my friend's Win10 and ran it again, but it still didn't work. Please help me and wait for your reply.

running info:

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of undefined
    at GotError.get (D:\Study\Node.js\Epic-auto\epicgames-freebies-claimer\node_modules\nested-error-stacks\index.js:22:52)
    at formatError (internal/util/inspect.js:1085:19)
    at formatRaw (internal/util/inspect.js:892:14)
    at formatValue (internal/util/inspect.js:746:10)
    at Object.inspect (internal/util/inspect.js:287:10)
    at Object.exports.format (D:\Study\Node.js\Epic-auto\epicgames-freebies-claimer\node_modules\tracer\lib\utils.js:22:22)
    at logMain (D:\Study\Node.js\Epic-auto\epicgames-freebies-claimer\node_modules\tracer\lib\console.js:53:25)
    at Object._self.<computed> [as error] (D:\Study\Node.js\Epic-auto\epicgames-freebies-claimer\node_modules\tracer\lib\console.js:151:12)
    at D:\Study\Node.js\Epic-auto\epicgames-freebies-claimer\claimer.js:116:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Revadike** [comment]
Hmm, that error is really not descriptive. I'm not sure what I can suggest other than a complete reinstall.

**Comment by ZainCheung** [comment]
> Hmm, that error is really not descriptive. I'm not sure what I can suggest other than a complete reinstall.

Well, still thank you, I will try other methods.

**Comment by ZainCheung** [comment]
Good news, I made it!
Previously I always got an error using cmd window that prevented me from running it, now I can run `npm install` and `npm start` in sequence using powershell to run the program properly, thank you!
