### ISSUE TITLE
TypeError: Cannot read property 'Catalog' of undefined

### ISSUE THREAD

**Issue by Fzoss** [Revadike/epicgames-freebies-claimer#102]
### Expected Behavior

run
### Actual Behavior

error
### Steps to Reproduce the Problem

  1. npm start

> epicgames-freebies-claimer@1.5.0 start
> node claimer.js

 2021-06-11 | 09:46:22.376 | INFO  | Logged in as xxx (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
 2021-06-11 | 09:46:43.383 | ERROR | TypeError: Cannot read property 'Catalog' of undefined
    at freeGamesPromotions (C:\Users\blues\Desktop\epic\epicgames-freebies-claimer\src\gamePromotions.js:5:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\blues\Desktop\epic\epicgames-freebies-claimer\claimer.js:56:30
### Specifications

  - `epicgames-freebies-claimer` Version: 1.5.0
  - Platform / OS: Windows 21H1
  - Node Version: v16.3.0

**Comment by Revadike** [comment]
Try V1.5.1
