### ISSUE TITLE
No history.json in the repositories 

### ISSUE THREAD

**Issue by lhllhx** [Revadike/epicgames-freebies-claimer#112]
### Expected Behavior
run well

### Actual Behavior
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\Administrator\Desktop\epicgame/history.json'
Require stack:
- C:\Users\Administrator\Desktop\epicgame\claimer.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\epicgame\claimer.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Administrator\\Desktop\\epicgame\\claimer.js' ]
}
```

### Specifications

  - `epicgames-freebies-claimer` Version:  1.5.2

**Comment by Revadike** [comment]
Fixed in V1.5.3
