### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by klwid04** [Revadike/epicgames-freebies-claimer#156]
After downloading and doing everything what is in documentation, I get this error when, I run npm start.
PS C:\Users\klwid\Downloads\epicgames-freebies-claimer-master> npm start

> epicgames-freebies-claimer@1.5.6 start
> node claimer.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'epicgames-client'
Require stack:
- C:\Users\klwid\Downloads\epicgames-freebies-claimer-master\claimer.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\klwid\Downloads\epicgames-freebies-claimer-master\claimer.js:11:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\klwid\\Downloads\\epicgames-freebies-claimer-master\\claimer.js'
  ]

**Comment by klwid04** [comment]
OMG Sorry I forgor to imput npm install smh

**Comment by Revadike** [comment]
I'm glad you sorted it out!

**Comment by SireBebeMichelin** [comment]
Hey I got the same but the installation seemed successful 
`PS` C:\Users\SirBebe_Michelin\Downloads\epicgames-freebies-claimer-master> npm install

up to date, audited 294 packages in 876ms

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\SirBebe_Michelin\Downloads\epicgames-freebies-claimer-master> npm start

> epicgames-freebies-claimer@1.5.8 start
> node claimer.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\SirBebe_Michelin\Downloads\epicgames-freebies-claimer-master/data/device_auths.json'
Require stack:
- C:\Users\SirBebe_Michelin\Downloads\epicgames-freebies-claimer-master\claimer.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\SirBebe_Michelin\Downloads\epicgames-freebies-claimer-master\claimer.js:14:15)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\SirBebe_Michelin\\Downloads\\epicgames-freebies-claimer-master\\claimer.js'
  ]
}

Node.js v17.4.0
PS `C:\Users\SirBebe_Michelin\Downloads\epicgames-freebies-claimer-master>`
