### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by RgazHTale** [Revadike/epicgames-freebies-claimer#200]
### Details
In Windows, I have set device_auths.json but prompted the question. Linux is same.
### Background (if needed)

![](https://cdn.jsdelivr.net/gh/RgazHTale/blog-img/202204152147755.png)
![](https://cdn.jsdelivr.net/gh/RgazHTale/blog-img/202204152147500.png)

**Comment by mattthhdp** [comment]
Same error here 

 ```
2022-04-19 | 00:19:25.164 | INFO  | Epicgames Freebies Claimer (1.5.8) by Revadike
 2022-04-19 | 00:19:26.000 | ERROR | TypeError: Cannot read properties of undefined (reading 'id')
    at getOfferId (/app/src/gamePromotions.js:42:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/src/gamePromotions.js:59:33
    at async Promise.all (index 0)
    at async freeGamesPromotions (/app/src/gamePromotions.js:57:22)
    at async /app/claimer.js:91:30
```

**Comment by zzz6839** [comment]
same 

> 22-04-21 | 13:17:52.675 | INFO | Epicgames Freebies Claimer (1.5.8) by Revadike[39m
m 2022-04-21 | 13:17:57.520 | ERROR | TypeError: Cannot read properties of undefined (reading 'id')[39m[22m
m at getOfferId (/app/src/gamePromotions.js:42:25)[39m[22m
m at processTicksAndRejections (node:internal/process/task_queues:96:5)[39m[22m
m at async /app/src/gamePromotions.js:59:33[39m[22m
m at async Promise.all (index 0)[39m[22m
m at async freeGamesPromotions (/app/src/gamePromotions.js:57:22)[39m[22m
m at async /app/claimer.js:91:30[39m[22m

**Comment by Revadike** [comment]
https://gist.github.com/Revadike/fddf757b8d2a1ae8ba3aa233ee6f2b67

**Comment by jamespdaily** [comment]
@Revadike does that json file go in the data folder? Can't seem to get it to work

**Comment by Revadike** [comment]
No, I just saved it for testing later.

**Comment by mirikking** [comment]
@Revadike, hi, any news about adding captcha resolve with payment service?
Btw, i trying to got final captcha token, how it possible?

**Comment by Revadike** [comment]
They have custom captchas and use a custom encrypted response. It's really hard. Not only that, tinkering with it got my main account banned. That's where I'm at.

**Comment by mirikking** [comment]
@Revadike, have idea how to get this?

**Comment by sewe2000** [comment]
I think I've found the cause of this error. In the epicgames-client module in the function getProductForSlug there is a wrong http request which returns just: { "Error" : true } in json.

**Comment by Chenilove** [comment]
If you have a solution, give me a kick

**Comment by astranberg** [comment]
> | ERROR | TypeError: Cannot read property 'id' of undefined
>     at getOfferId (A:\epicgames-freebies-claimer-master\src\gamePromotions.js:42:25)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async A:\epicgames-freebies-claimer-master\src\gamePromotions.js:59:33
>     at async Promise.all (index 1)
>     at async freeGamesPromotions (A:\epicgames-freebies-claimer-master\src\gamePromotions.js:57:22)
>     at async A:\epicgames-freebies-claimer-master\claimer.js:91:30

so this is a CAPTCHA issue then? This repo no longer works then..?

**Comment by fantnhu** [comment]
same
