### ISSUE TITLE
TypeError not a function

### ISSUE THREAD

**Issue by lolozeeniboss** [Revadike/epicgames-freebies-claimer#37]
I have this issue since the last pull
```
 2020-06-14 | 14:25:14.393 | INFO  | Logged in as xxxxxxxxxx(xxxxxxxxxxxxxxxxxxxxxx)
 2020-06-14 | 14:25:14.396 | ERROR | TypeError: client.freeGamesPromotions is not a function
    at freeGamesPromotions (D:\xxxxxxxx\epicgames-freebies-claimer\claimer.js:28:33)
    at D:\xxxxxxx\epicgames-freebies-claimer\claimer.js:91:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Process finished with exit code 1
```

**Comment by luclu** [comment]
Error appears for only on Docker's node image - no problem on macOS.
```
 2020-07-11 | 10:53:04.032 | INFO  | Logged in as ar-ion (ad5022e1d158400283779c0c66e5c42c)
 2020-07-11 | 10:53:04.034 | ERROR | TypeError: client.freeGamesPromotions is not a function
    at freeGamesPromotions (/epicgames-freebies-claimer/claimer.js:28:33)
    at /epicgames-freebies-claimer/claimer.js:91:36
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.1 start: `node claimer.js`
npm ERR! Exit status 1```

**Comment by louga31** [comment]
Fixed the issue in my fork:
Replace your package.json by this (It just changes the epicgames-client source to my fork and change the version number):
```json
{
    "name": "epicgames-freebies-claimer",
    "version": "2.0.25",
    "description": "Claim free game promotions from the Epic Game Store",
    "author": "Revadike <https://revadike.com>",
    "main": "claimer.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "start": "node claimer.js"
    },
    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/revadike/epicgames-freebies-claimer.git"
    },
    "bugs": {
        "url": "https://github.com/revadike/epicgames-freebies-claimer/issues"
    },
    "homepage": "https://github.com/revadike/epicgames-freebies-claimer",
    "url": "https://github.com/revadike/epicgames-freebies-claimer",
    "devDependencies": {
        "eslint": "^6.8.0"
    },
    "dependencies": {
        "check-update-github": "0.0.4",
        "colors": "^1.4.0",
        "epicgames-client": "github:louga31/node-epicgames-client#master",
        "epicgames-client-login-adapter": "^0.1.2",
        "node-2fa": "^1.1.2",
        "tracer": "^1.1.2"
    }
}
```
It should fix it

**Comment by Revadike** [comment]
Perform `npm install` or `npm update`
