### ISSUE TITLE
Value error 

### ISSUE THREAD

**Issue by Oli2004** [Revadike/epicgames-freebies-claimer#60]
every time i try to use it it get to the logged in then this happen 
 2020-10-12 | 02:24:17.199 | ERROR | TypeError: Cannot read property 'value' of undefined
    at Launcher.enableTwoFactor (C:\Users\Oli\Desktop\epicgames-freebies-claimer-1.4.1\node_modules\epicgames-client\src\Client\index.js:1226:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Oli\Desktop\epicgames-freebies-claimer-1.4.1\claimer.js:74:17
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.0 start: `node claimer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epicgames-freebies-claimer@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Oli\AppData\Roaming\npm-cache\_logs\2020-10-12T02_24_17_250Z-debug.log

**Comment by Revadike** [comment]
Can you verify if this still happens with the latest version? Closing this issue for now...
