### ISSUE TITLE
e.isFile is not a function

### ISSUE THREAD

**Issue by 7exe** [Revadike/epicgames-freebies-claimer#62]
As soon as the node.js script is runned, it exits immediately with the following error:
TypeError: e.isFile is not a function
    at readdir.forEach (D:\epic-games-claimer\epicgames-freebies-claimer\node_modules\epicgames-client\resources\GraphQL.js:8:11)
    at Array.forEach (<anonymous>)
    at getGraphQL (D:\epic-games-claimer\epicgames-freebies-claimer\node_modules\epicgames-client\resources\GraphQL.js:7:39)
    at Object.<anonymous> (D:\epic-games-claimer\epicgames-freebies-claimer\node_modules\epicgames-client\resources\GraphQL.js:17:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)

**Comment by fatinghenji** [comment]
same problem

**Comment by Revadike** [comment]
Can you verify if this still happens with the latest version? Closing this issue for now...
