### ISSUE TITLE
idfk what that means, failed to npm start

### ISSUE THREAD

**Issue by MrZeroLord** [Revadike/epicgames-freebies-claimer#64]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\dspla\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.13.2
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle epicgames-freebies-claimer@1.4.1~prestart: epicgames-freebies-claimer@1.4.1
6 info lifecycle epicgames-freebies-claimer@1.4.1~start: epicgames-freebies-claimer@1.4.1
7 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: PATH: C:\Users\dspla\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\epicgames-freebies-claimer-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Users\dspla\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\dspla\AppData\Local\Programs\Python\Python36\;C:\Users\dspla\AppData\L;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Python27;C:\Python27\Scripts;C:\Users\dspla\AppData\Local\Microsoft\WindowsApps;C:\Users\dspla\AppData\Local\atom\bin;C:\Users\dspla\AppData\Roaming\npm;C:\Users\dspla\AppData\Local\Microsoft\WindowsApps;C:\webdrivers\chromedriver.exe;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3\bin
9 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: CWD: C:\epicgames-freebies-claimer-master
10 silly lifecycle epicgames-freebies-claimer@1.4.1~start: Args: [ '/d /s /c', 'node claimer.js' ]
11 silly lifecycle epicgames-freebies-claimer@1.4.1~start: Returned: code: 1  signal: null
12 info lifecycle epicgames-freebies-claimer@1.4.1~start: Failed to exec start script
13 verbose stack Error: epicgames-freebies-claimer@1.4.1 start: `node claimer.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\dspla\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\dspla\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid epicgames-freebies-claimer@1.4.1
15 verbose cwd C:\epicgames-freebies-claimer-master
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dspla\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.3
19 verbose npm  v6.13.2
20 error code ELIFECYCLE
21 error errno 1
22 error epicgames-freebies-claimer@1.4.1 start: `node claimer.js`
22 error Exit status 1
23 error Failed at the epicgames-freebies-claimer@1.4.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by MrZeroLord** [comment]
![image](https://user-images.githubusercontent.com/40106969/97081564-7cd55200-1603-11eb-8be5-7117c6de9549.png)

**Comment by MrZeroLord** [comment]
I'm dumb
