### ISSUE TITLE
Timeout error, I can't find how to fix it

### ISSUE THREAD

**Issue by FolfyBlue** [Revadike/epicgames-freebies-claimer#66]
Here's the error:
```
PS C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1> npm start

> epicgames-freebies-claimer@1.4.1 start C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1
> node claimer.js

 2020-11-06 | 13:03:53.059 | WARN  | Failed to login as folfyblu@gmail.com, please attempt manually.
 2020-11-06 | 13:04:32.302 | ERROR | TimeoutError: waiting for selector "#login:not(:disabled)" failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1\node_modules\puppeteer\lib\DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1\node_modules\puppeteer\lib\DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1\node_modules\puppeteer\lib\DOMWorld.js:432:17)
    at Frame.waitForSelector (C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1\node_modules\puppeteer\lib\FrameManager.js:627:47)
    at Frame.<anonymous> (C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.waitForSelector (C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1\node_modules\puppeteer\lib\Page.js:1122:29)
    at Function.init (C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1\node_modules\epicgames-client-login-adapter\index.js:107:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\folfy\Desktop\gamefarm\epicgames-freebies-claimer-1.4.1\claimer.js:79:28
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.1 start: `node claimer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epicgames-freebies-claimer@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\folfy\AppData\Roaming\npm-cache\_logs\2020-11-06T12_04_32_502Z-debug.log
```

**Comment by Huzukawaiii** [comment]
same

**Comment by c4ffein** [comment]
Any updates @Revadike ? That script would save me some time but it seems broken as is, at least when connecting from a new device, and I want to know if this repo is still maintained or if I should try to fix it myself.

**Comment by Revadike** [comment]
I haven't looked at it for a while

**Comment by GuFFy12** [comment]
same

**Comment by dodgythoughts** [comment]
Edit
epicgames-freebies-claimer/node_modules/puppeteer/lib/TimeoutSettings.js
change 
const DEFAULT_TIMEOUT = 30000;  

30000 = 30 seconds, Epic games login screen gives you the spinning wheel for longer than this. I changed mine to 120 seconds.

**Comment by FolfyBlue** [comment]
Changing the timeout doesn't change much, I can now log in into the appearing tab, but it still crashes

**Comment by Revadike** [comment]
This should be fixed now
