### ISSUE TITLE
I'm using Glitch to run this app. I don't know what's happening

### ISSUE THREAD

**Issue by GiomboHotdog** [Revadike/epicgames-freebies-claimer#67]
I imported this rep on Glitch and configured the config.json .When I try `npm start` there is an error. I don't know what happened so I'll just put the console log here

```
Welcome to the Glitch console

If you’re following someone else’s instructions make sure you trust them.
If in doubt post a question in our forum https://support.glitch.com

For now, the console and the editor don't automatically sync. You can
manually run the `refresh` command and it will force a refresh,
updating the editor with any console-created files.

For more information about this and other technical restrictions,
please see the Help Center: https://glitch.com/help

Could not find Node null, using Node 10

app@free-epicgames-claimer:~ 08:17 
$ npm start

> epicgames-freebies-claimer@1.4.1 start /app
> node claimer.js

 2020-11-15 | 08:18:53.251 | ERROR | { Error: ENOENT: no such file or directory, mkdir '/app/.egstore/2bad408ffcc3317ec1a30f112e11c6a309be489504114222fc202af5392ca43f'
    at Object.mkdirSync (fs.js:752:3)
    at new Launcher (/rbd/pnpm-volume/b5f8135b-88d0-4fe9-865a-7987c777361e/node_modules/.github.com/Revadike/node-epicgames-client/73274228e55b109de8a414cc8a6551ce4879f3dc/node_modules/epicgames-client/src/Client/index.js:109:10)
    at /app/claimer.js:79:26
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path:
   '/app/.egstore/2bad408ffcc3317ec1a30f112e11c6a309be489504114222fc202af5392ca43f' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.1 start: `node claimer.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the epicgames-freebies-claimer@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/10.15.3/_logs/2020-11-15T08_18_53_532Z-debug.log
```

**Comment by giacomoferretti** [comment]
As the log says, there is an ENOENT error. The program tries to [create a directory](https://github.com/Revadike/node-epicgames-client/blob/master/src/Client/index.js#L107), but it can't because you cannot create directories on Glitch. 

Reference: https://stackoverflow.com/questions/61579314/fs-mkdir-and-fs-writefile-dont-work-in-glitch-hosting

**Comment by GiomboHotdog** [comment]
I see, thanks for the heads up!
