### ISSUE TITLE
why show this error?

### ISSUE THREAD

**Issue by zhimingoh** [Revadike/epicgames-freebies-claimer#68]
(node:25612) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of undefined
    at GotError.get (F:\epicgames-freebies-claimer-master\node_modules\nested-error-stacks\index.js:22:52)
    at formatError (internal/util/inspect.js:907:19)
    at formatRaw (internal/util/inspect.js:703:14)
    at formatValue (internal/util/inspect.js:591:10)
    at Object.inspect (internal/util/inspect.js:221:10)
    at Object.exports.format (F:\epicgames-freebies-claimer-master\node_modules\tracer\lib\utils.js:22:22)
    at logMain (F:\epicgames-freebies-claimer-master\node_modules\tracer\lib\console.js:53:25)
    at Object._self.<computed> [as error] (F:\epicgames-freebies-claimer-master\node_modules\tracer\lib\console.js:151:12)
    at F:\epicgames-freebies-claimer-master\claimer.js:171:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:25612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Kill4peacE** [comment]
same

**Comment by AmazingXiaomi** [comment]
same

**Comment by Revadike** [comment]
Can you verify if this still happens with the latest version? Closing this issue for now...
