### ISSUE TITLE
Unexpected token # in JSON at position 151

### ISSUE THREAD

**Issue by crsleeth** [Revadike/epicgames-freebies-claimer#71]
Ubuntu 20.04.1 (headless), nodejs version 15.5.0, npm version 7.3.0
```
> epicgames-freebies-claimer@1.4.1 start
> node claimer.js

node:internal/modules/cjs/loader:1154
    throw err;
    ^

SyntaxError: /home/ryan/epicgames-freebies-claimer/config.json: Unexpected token # in JSON at position 151
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1151:22)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/ryan/epicgames-freebies-claimer/claimer.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
npm ERR! code 1
npm ERR! path /home/ryan/epicgames-freebies-claimer
npm ERR! command failed
npm ERR! command sh -c node claimer.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ryan/.npm/_logs/2020-12-24T10_38_48_049Z-debug.log
```

**Comment by crsleeth** [comment]
Similar issue happens on Windows 10, nodejs version 12.18.4
```
> epicgames-freebies-claimer@1.4.1 start C:\Users\Ryan\epicgames-freebies-claimer-master
> node claimer.js

internal/modules/cjs/loader.js:1174
    throw err;
    ^

SyntaxError: C:\Users\Ryan\epicgames-freebies-claimer-master\config.json: Unexpected token ] in JSON at position 144
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Ryan\epicgames-freebies-claimer-master\claimer.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.1 start: `node claimer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epicgames-freebies-claimer@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ryan\AppData\Roaming\npm-cache\_logs\2020-12-24T13_37_51_252Z-debug.log
```

**Comment by crsleeth** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle epicgames-freebies-claimer@1.4.1~prestart: epicgames-freebies-claimer@1.4.1
6 info lifecycle epicgames-freebies-claimer@1.4.1~start: epicgames-freebies-claimer@1.4.1
7 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Ryan\epicgames-freebies-claimer-master\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\Ryan\AppData\Local\Microsoft\WindowsApps;C:\Users\Ryan\AppData\Roaming\npm
9 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: CWD: C:\Users\Ryan\epicgames-freebies-claimer-master
10 silly lifecycle epicgames-freebies-claimer@1.4.1~start: Args: [ '/d /s /c', 'node claimer.js' ]
11 silly lifecycle epicgames-freebies-claimer@1.4.1~start: Returned: code: 1  signal: null
12 info lifecycle epicgames-freebies-claimer@1.4.1~start: Failed to exec start script
13 verbose stack Error: epicgames-freebies-claimer@1.4.1 start: `node claimer.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid epicgames-freebies-claimer@1.4.1
15 verbose cwd C:\Users\Ryan\epicgames-freebies-claimer-master
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.18.4
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error epicgames-freebies-claimer@1.4.1 start: `node claimer.js`
22 error Exit status 1
23 error Failed at the epicgames-freebies-claimer@1.4.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Revadike** [comment]
Looks like you broke the JSON syntax in `config.json`
