### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by qq995764533** [Revadike/epicgames-freebies-claimer#90]
system：debian 10
  I have installed git, downloaded and decompressed the source code, installed node.js using apt, run npm install error, prompting that the npm command does not exist. I installed it using apt install npm and it was successful. npm start email passwora 2fa, prompts that the npm version may be incompatible, epicgame-client is not found, and the script fails to run.
![run](https://user-images.githubusercontent.com/45648638/111292742-7794a480-8683-11eb-9e22-1b02fe3f7402.png)
![install npm](https://user-images.githubusercontent.com/45648638/111292751-7b282b80-8683-11eb-8aac-29b7ccdd98d7.png)

**Comment by Revadike** [comment]
It says node_modules is missing, so you don't seem to have installed the dependencies correctly.

**Comment by qq995764533** [comment]
I installed node.js by another method and followed the steps. It prompted that the browser could not be run. I installed chrome-current, and then prompted that I could not open X-diplay. I solved it through online teaching, and the following appeared again. Should it be a login timeout? I want to ask if this project needs to have a GUI interface to display 2fa. I am trying to run it on an Ubuntu system without a GUI interface.Thanks.
2021-03-17 | 10:18:53.609 | WARN  | Invalid captcha!
 2021-03-17 | 10:18:53.612 | WARN  | Failed to login as EMAIL, please attempt manually.
 2021-03-17 | 10:19:33.845 | ERROR | TimeoutError: waiting for selector "#login:not(:disabled)" failed: timeout 30000ms exceeded
    at new WaitTask (/home/ubuntu/epicgames-freebies-claimer-master/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/home/ubuntu/epicgames-freebies-claimer-master/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/home/ubuntu/epicgames-freebies-claimer-master/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/home/ubuntu/epicgames-freebies-claimer-master/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/home/ubuntu/epicgames-freebies-claimer-master/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/home/ubuntu/epicgames-freebies-claimer-master/node_modules/puppeteer/lib/Page.js:1122:29)
    at Function.authenticate (/home/ubuntu/epicgames-freebies-claimer-master/node_modules/epicgames-client-login-adapter/index.js:119:38)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Function.init (/home/ubuntu/epicgames-freebies-claimer-master/node_modules/epicgames-client-login-adapter/index.js:204:7)
    at async /home/ubuntu/epicgames-freebies-claimer-master/claimer.js:110:28

**Comment by Revadike** [comment]
Sorry, it does need a GUI for manual 2fa solving.
