### ISSUE TITLE
Error at npm start.

### ISSUE THREAD

**Issue by BenjaminJacober** [Revadike/epicgames-freebies-claimer#96]
Don't know too much about js. It told me that babel is missing and i installed it. Beyond that it's too much for me.

```
sudo npm start
> epicgames-freebies-claimer@1.5.0 start /home/benij/Software/epicgames-game-claimer/epicgames-freebies-claimer
> node claimer.js
 2021-05-31 | 12:16:24.998 | ERROR | Error: ENOENT: no such file or directory, mkdir '/home/benij/Software/epicgames-game-claimer/epicgames-freebies-claimer/.egstore/b3c08289c9c960beb9cf91d3915a75d623b14374a25347ec3ec568ce7b202cd9'
    at Object.mkdirSync (fs.js:914:3)
    at new Launcher (/home/benij/Software/epicgames-game-claimer/epicgames-freebies-claimer/node_modules/epicgames-client/src/Client/index.js:110:10)
    at /home/benij/Software/epicgames-game-claimer/epicgames-freebies-claimer/claimer.js:43:26
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/benij/Software/epicgames-game-claimer/epicgames-freebies-claimer/.egstore/b3c08289c9c960beb9cf91d3915a75d623b14374a25347ec3ec568ce7b202cd9'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.5.0 start: `node claimer.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the epicgames-freebies-claimer@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-31T10_16_25_021Z-debug.log
```

**Comment by Revadike** [comment]
Try now
`npm uninstall`
`npm install`

**Comment by BenjaminJacober** [comment]
Already did that (kind of, deleted the node_modules folder). Tried again just in case, doesn't work. Where exactly do i have to put the device_auths file?

**Comment by Revadike** [comment]
Is there permissions to write to '/home/benij/Software/epicgames-game-claimer/epicgames-freebies-claimer/.egstore/b3c08289c9c960beb9cf91d3915a75d623b14374a25347ec3ec568ce7b202cd9'?

**Comment by BenjaminJacober** [comment]
Started npm with sudo rights. So yes, i am pretty sure the super user gets to do that.

**Comment by Revadike** [comment]
Try `sudo npm install --unsafe-perm=true --allow-root`

**Comment by Revadike** [comment]
It's the same error you're getting?

**Comment by BenjaminJacober** [comment]
Nope, works fine now. Thanks mate. Gonna add this to startup.

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/43
